<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CQRS.Domain.Shared\CQRS.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\src\Cike.Data.Domain\Cike.Data.Domain.csproj" />
  </ItemGroup>

</Project>
